apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-proxy
    spec:
      containers:
        - image: nginx:1.19.10
          name: nginx-proxy
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-proxy-claim0
              readOnly: true
      hostname: nginx-proxy
      restartPolicy: Always
      volumes:
        - name: nginx-proxy-claim0
          persistentVolumeClaim:
            claimName: nginx-proxy-claim0
            readOnly: true
status: {}
